### PR TITLE
Strings are now written in UTF-8

### PR DESCRIPTION
**Pull request by GerritDamen**
I had massive problems while trying to serve utf8 content. Fed up with encapsulating my strings in a bunch of encode-functions I decided to just hack your wsgi server to write Utf8 strings directly.

This is just a quick hack, I'm always happy about some feedback, e.g. if this was something very stupid I did.

### CODE REVIEW

**Comment by SimonSapin** [comment]
Strings encoding in WSGI is [a big mess](http://lucumr.pocoo.org/2010/5/25/wsgi-on-python-3/#the-about-to-be-spec). The spec [mandates](https://www.python.org/dev/peps/pep-3333/#unicode-issues) Latin-1 here.

But for the `write` function, you should really just give it bytes to begin with. Use `.encode('utf-8')` in your own code.

**Comment by SimonSapin** [comment]
Also, unless you write WSGI directly, most web frameworks should take care of this for you. Have a look at [Flask](http://flask.pocoo.org/) for example.

**Comment by GerritDamen** [comment]
Thank you very much for the links, I'll try some different approaches then. 
I write WSGI directly, that's why I ran into these problems.

**Comment by SimonSapin** [comment]
> I write WSGI directly

I recommend pretending that the response body must be bytes and doing the encoding from Unicode yourself.

**Pull request closed without merging**
